#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,hyprland,nvim,tmux,zsh,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/personal/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
