#!/usr/bin/env bash

set -euo pipefail

pushd "$DOTFILES" > /dev/null

IFS=',' read -ra FOLDERS <<< "$STOW_FOLDERS"
for folder in "${FOLDERS[@]}"; do
    echo "stow $folder"
    stow -t "$HOME" -D "$folder"
    stow -t "$HOME" "$folder"

    if [[ -f "extras/$folder" ]]; then
        . "extras/$folder"
    fi
done

popd > /dev/null
